### ISSUE TITLE
HCL2020数据下载

### ISSUE THREAD

**Issue by Jonsun-N** [kaka0910/HCL2020#2]
请问可以给个HCL2020的数据下载地址么

**Comment by memorylorry** [comment]
同求数据！

**Comment by kaka0910** [comment]
可以发邮件到xumengqiu@bupt.edu.cn

**Comment by memorylorry** [comment]
案例参考
https://developer.huaweicloud.com/develop/aigallery/notebook/detail?id=8c23220b-9928-48e9-92bc-c322dd3bde99
